os: osx
sudo: required
language: generic
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
      ⋮
  - rvm install 2.3.3
  - rvm use 2.3.3
  - gem install cucumber
  - gem install gherkin
  - gem install webdrivers
  - gem install chromedriver-helper
#  - wget http://chromedriver.storage.googleapis.com/2.30/chromedriver_mac64.zip
#  - unzip chromedriver_mac64.zip -d ~/
#  - sudo mv -f ~/chromedriver /usr/local/share/
#  - sudo chmod +x /usr/local/share/chromedriver
#  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
#  - gem install hiptest-publisher
#  - hiptest-publisher -c hiptest-publisher.conf --token=1429811748290606834100832667303749663843214613307688107 --test-run-id=301761
script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - cucumber