sudo: required
language: generic
before_install:
  - rvm install 2.3.3
  - rvm use 2.3.3
  - gem install cucumber
  - gem install gherkin
  - gem install selenium-webdriver
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/ruby2.3.3/bin/
  - export CHROME_BIN=chromium-browser
#  - gem install hiptest-publisher
#  - hiptest-publisher -c hiptest-publisher.conf --token=1429811748290606834100832667303749663843214613307688107 --test-run-id=301761
script:
  - cucumber