os: osx
sudo: required
language: generic
addons:
  chrome: stable
notifications:
  slack: gamingxlife:VcLyLdO7JWpWgypjiQxML30w
before_install:
  - gem install cucumber
  - gem install gherkin
  - gem install webdrivers
  - gem install rspec
  - gem install rspec-expectations
  - HOMEBREW_NO_AUTO_UPDATE=1 brew cask install chromedriver
  - gem install chromedriver-helper
#  - gem install hiptest-publisher
#  - hiptest-publisher -c hiptest-publisher.conf --token=1429811748290606834100832667303749663843214613307688107 --test-run-id=301761
script:
  - cucumber